### ISSUE TITLE
How to make custom bundle?

### ISSUE THREAD

**Issue by PerpetualWar** [plotly/plotly-webpack#12]
In this repo I don't see a way to make custom bundle. Where can I see how to do that?

Considering I only use line, bar and treemap charts (and treemap is not included in any partial bundle), it seems insane to use full bundle in my case.

Help appreciated.

**Comment by nicolaskruchten** [comment]
There are some instructions under https://github.com/plotly/plotly.js/#modules

**Comment by PerpetualWar** [comment]
> There are some instructions under https://github.com/plotly/plotly.js/#modules

Thanks, appreciated ;)
