### ISSUE TITLE
Error running with plotly.js 1.41.3: Can't resolve 'plotly.js/tasks/util/compress_attributes.js'

### ISSUE THREAD

**Issue by pydolan** [plotly/plotly-webpack#7]
I tried using this repository as instructed (npm install; npm run webpack-dev`), and I received the following error: Can't resolve 'plotly.js/tasks/util/compress_attributes.js'.  

I checked the Plotly.js version, and it installed 1.41.3.  Switching the package.json dependency to "plotly.js": "~1.33.0" fixes this error.

**Comment by nicolaskruchten** [comment]
@antoinerg can you take a look at this please?

**Comment by etpinard** [comment]
`compress_attributes` was moved to -> `tasks/compress_attributes.js`

https://github.com/plotly/plotly.js/blob/master/tasks/compress_attributes.js

**Comment by nicolaskruchten** [comment]
Ah ok, should be easy to patch https://github.com/plotly/plotly-webpack/blob/master/webpack.config.js#L16 :)

**Comment by etpinard** [comment]
Hmm. Can I get write rights to this repo?

**Comment by nicolaskruchten** [comment]
@etpinard done
