### ISSUE TITLE
Remove references to babel

### ISSUE THREAD

**Issue by paulovieira** [plotly/plotly-webpack#9]
In the current readme we have

```
Bundling for production with webpack by default runs the UglifyJS plugin, 
which doesn't accept ES6 syntax[...]
```

But this is not true anymore with webpack 4 (for over a year, see: https://github.com/webpack/webpack/pull/8036).

By default webpack now uses Terser (via terser-webpack-plugin), which works fine with ES6+. So the webpack configuration can be simplified by removing babel.

This is done in PR .#10

**Comment by etpinard** [comment]
Done in https://github.com/plotly/plotly-webpack/pull/10

Thanks again @paulovieira !
